### ISSUE TITLE
incorrect capability used

### ISSUE THREAD

**Issue by danmarsden** [corvus-albus/moodle-local_wsmanagesections#1]
https://github.com/corvus-albus/moodle-local_wsmanagesections/blob/master/externallib.php#L184

shouldn't that be checking course:update not course:view?

**Comment by corvus-albus** [comment]
Thank you. That's for sure. Deleting isn't covered by viewing.
I'll change it.

**Comment by corvus-albus** [comment]
It is fixed in release 0.9.6.3.
