### ISSUE TITLE
local_wsmanagesections_update_sections breaks when setting availability

### ISSUE THREAD

**Issue by Arzerilla** [corvus-albus/moodle-local_wsmanagesections#3]
curl --location -g --request GET 'http://localhost/moodle/webservice/rest/server.php?wstoken=[mytoken]&moodlewsrestformat=json&wsfunction=local_wsmanagesections_update_sections&courseid=2&sections[0][type]=num&sections[0][section]=4&sections[0][name]=four&sections[0][sectionformatoptions][0][name]=availability&sections[0][sectionformatoptions][0][value]={"op":"%26","c":[{"type":"date","d":">=","t":1540991600},{"type":"date","d":"<","t":1664575200}],"showc":[true,true]}'

If you try to set availability for a section it breaks cause json string is parsed as a PARAM_TEXT.

To fix that edit wsmanagesections\externallib.php , function update_sections_parameters at line 519
                FROM                        'value' => new external_value(**PARAM_TEXT**, 'section format option value')
                TO                             'value' => new external_value(**PARAM_RAW**, 'section format option value')

**Comment by corvus-albus** [comment]
Hope it works now. Thank you for your detailed instruction!

**Comment by corvus-albus** [comment]
Should be fixed now.
